version: "2"
run:
  modules-download-mode: vendor
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - funcorder
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - govet
    - intrange
    - ireturn
    - lll
    - mnd
    - modernize
    - musttag
    - nestif
    - nlreturn
    - noinlineerr
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - recvcheck
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - generated
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - generated
      - third_party$
      - builtin$
      - examples$
