package veneers

import (
	"github.com/grafana/cog/internal/veneers/builder"
	"github.com/grafana/cog/internal/veneers/option"
)

func Common() *Rewriter {
	dashboardPanelOptionsToExclude := []string{
		"id",            // generated by the backend
		"fieldConfig",   // merged with another builder
		"options",       // comes from a panel plugin
		"custom",        // comes from a panel plugin
		"pluginVersion", // TODO: check if it's relevant or not
		"repeatPanelId", // TODO: check if it's relevant or not
		"tags",          // TODO: check if it's relevant or not
	}

	return NewRewrite(
		[]builder.RewriteRule{
			/********************************************
			 * Dashboards
			 ********************************************/

			// We don't want these builders at all
			builder.Omit(builder.ByObjectName("dashboard.GridPos")),
			builder.Omit(builder.ByObjectName("dashboard.DataSourceRef")),
			builder.Omit(builder.ByObjectName("dashboard.LibraryPanelRef")),

			// rearrange things a bit
			builder.MergeInto(
				builder.ByObjectName("dashboard.Panel"),
				"dashboard.FieldConfig",
				"fieldConfig.defaults",

				[]string{
					// don't copy these over as they clash with a similarly named options from Panel
					"description", "links",

					// TODO: check if these are actually relevant
					"displayNameFromDS", "filterable", "path", "writeable",
				},
			),

			// Panels composability
			builder.ComposeDashboardPanel(
				builder.ComposableDashboardPanel(),
				"dashboard.Panel",
				dashboardPanelOptionsToExclude,
			),

			// remove builders that were previously merged into something else
			builder.Omit(builder.ByObjectName("dashboard.FieldConfig")),
			builder.Omit(builder.ByObjectName("dashboard.FieldConfigSource")),

			// No need for builders for structs generated from a disjunction
			builder.Omit(builder.StructGeneratedFromDisjunction()),
		},

		[]option.RewriteRule{
			/********************************************
			 * Dashboards
			 ********************************************/

			// Let's make the dashboard constructor more friendly
			option.PromoteToConstructor(
				option.ByName("Dashboard", "title"),
			),

			// `Tooltip` looks better than `GraphTooltip`
			option.Rename(
				option.ByName("Dashboard", "graphTooltip"),
				"tooltip",
			),

			// Append a single `panel|row` value instead of a list of everything
			option.ArrayToAppend(
				option.ByName("Dashboard", "panels"),
			),
			// Panel(...) and RowPanel(...) instead of panels(...(Panel|RowPanel))
			option.DisjunctionAsOptions(
				option.ByName("Dashboard", "panels"),
			),
			// RowPanel() to Row()
			option.Rename(
				option.ByName("Dashboard", "rowPanel"),
				"row",
			),

			// Editable() + Readonly() instead of Editable(val bool)
			option.UnfoldBoolean(
				option.ByName("Dashboard", "editable"),
				option.BooleanUnfold{OptionTrue: "editable", OptionFalse: "readonly"},
			),

			// Refresh(string) instead of Refresh(struct StringOrBool)
			option.StructFieldsAsArguments(
				option.ByName("Dashboard", "refresh"),
				"String",
			),

			// We don't want these options at all
			option.Omit(option.ByName("Dashboard", "schemaVersion")),

			/********************************************
			 * Panels
			 ********************************************/

			option.Omit(option.ByName("Panel", dashboardPanelOptionsToExclude...)),

			/********************************************
			 * Rows
			 ********************************************/

			// Let's make the row constructor more friendly
			/*
				option.PromoteToConstructor(
					option.ByName("RowPanel", "title"),
				),
			*/

			/********************************************
			 * Team
			 ********************************************/

			// Let's make the row constructor more friendly
			option.PromoteToConstructor(
				option.ByName("Team", "name"),
			),
		},
	)
}
