name: Java Release
on:
  pull_request_target:
    types: [ closed ]
    paths:
      - 'java/src/**'

env:
  JAVA_VERSION: '17'

jobs:
  release:
    if: github.event.pull_request.merged == true && github.base_ref == '{{ .Extra.ReleaseBranch }}'

    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./java

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java {{ `${{ env.JAVA_VERSION }}` }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Publish package 📦
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: current
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  
