name: Java CI
on:
  pull_request: ~

env:
  JAVA_VERSION: '17'

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./java

    steps:
      - name: Use Java SDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          check-latest: true

      - name: Test and build Jar
        uses: gradle/actions/setup-gradle@v3
        env:
          CHECK_GENERATED_FILES: true
        with:
          gradle-version: '8.8'
        run: gradle build
