name: Java CI
on:
  pull_request: ~

env:
  JAVA_VERSION: '17'

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./java

    steps:
      - uses: actions/checkout@v4

      - name: Use Java SDK {{ `${{ env.JAVA_VERSION }}` }}
        uses: actions/setup-java@v4
        with:
          java-version: {{ `${{ env.JAVA_VERSION }}` }}
          distribution: 'temurin'
          check-latest: true

      - name: Java setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Java build
        run: gradle build
