name: Go CI
on:
  pull_request: ~

env:
  GO_VERSION: '1.21'

jobs:
  golang:
    name: Go
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./go

    steps:
      - uses: actions/checkout@v4

      - name: Use Go {{ `${{ env.GO_VERSION }}` }}
        uses: actions/setup-go@v4
        with:
          go-version: {{ `${{ env.GO_VERSION }}` }}

      - name: Install dependencies
        run: go mod vendor

      - name: Go build
        run: |
          for d in */ ; do
            [[ "$d" != "docs/" ]] && (echo "Building $d"; go build "./$d")
          done
