debug: false

parameters:
  output_dir: './generated'
  kind_registry_path: '../kind-registry'
  kind_registry_version: 'v10.4.x'
  cog_version: 'v0.0.x'
  release_branch: 'release_branch'
  build_timestamp: 'build_timestamp'
  go_package_root: 'github.com/grafana/grafana-foundation-sdk/go'

inputs:
  - kind_registry:
      path: '%kind_registry_path%'
      version: '%kind_registry_version%'
      transformations:
        - '%__config_dir%/compiler/kind_registry.yaml'

transformations:
  schemas:
    - '%__config_dir%/compiler/common_passes.yaml'

  builders:
    - '%__config_dir%/veneers'

output:
  directory: '%output_dir%'

  types: true
  builders: true

  package_templates: '%__config_dir%/../package_templates'
  repository_templates: '%__config_dir%/../repository_templates'
  templates_data:
    GrafanaVersion: '%kind_registry_version%'
    CogVersion: '%cog_version%'
    ReleaseBranch: '%release_branch%'
    BuildTimestamp: '%build_timestamp%'

  languages:
    - go:
        go_mod: true
        package_root: '%go_package_root%'
    - jsonschema: {}
    - openapi: {}
    - python:
        path_prefix: grafana_foundation_sdk
    - typescript: {}
#    - java: {}
