debug: true

parameters:
  kind_registry_version: 'v10.4.x'
  release_branch: 'release_branch'
  build_timestamp: 'build_timestamp'

inputs:
  - jsonschema:
      path: ../expr.json
      package: expr
#  - openapi:
#      path: ../grafana-openapi3.json
  - kind_registry:
      path: '../../kind-registry'
      version: '%kind_registry_version%'

transformations:
  schemas:
    - ./compiler/common_passes.yaml

  builders:
    - ./veneers

output:
  directory: '../generated/%l'

  types: true
  builders: true

  package_templates: ../package_templates
  repository_templates: ../repository_templates
  templates_data:
    GrafanaVersion: '%kind_registry_version%'
    ReleaseBranch: '%release_branch%'
    BuildTimestamp: '%build_timestamp%'

  languages:
    - go:
        go_mod: true
        package_root: 'github.com/grafana/cog/foo'
#    - java: {}
    - jsonschema: {}
#    - openapi: {}
#    - python:
#        path_prefix: grafana_foundation_sdk
#    - typescript: {}
