language: all

package: heatmap

builders: ~

options:
  - struct_fields_as_arguments:
      by_name: Options.legend
  - struct_fields_as_arguments:
      by_name: Options.tooltip
  - struct_fields_as_arguments:
      by_name: Options.exemplars
