# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/pipeline.json

debug: true

parameters:
  output_dir: './testdata/%l'
  cue_path: '%__config_dir%/../testdata/schemas'

inputs:
  - cue:
      entrypoint: '%cue_path%'

output:
  directory: '%output_dir%'

  types: true

  languages: ~
