# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/pipeline.json

debug: true

parameters:
  output_dir: './generated/%l'
  grafana_version: 'main'
  go_package_root: 'github.com/grafana/cog/generated/go'
  php_namespace_root: 'Grafana\Foundation'
  java_package_path: 'com.grafana.foundation'

inputs:
  - k8:
      url: 'https://play.grafana.org/'
      transformations:
        - '%__config_dir%/foundation-sdk/.cog/compiler/k8.yaml'
      allowed_schemas:
        dashboard:
          version: 'v2beta1'

output:
  directory: '%output_dir%'

  types: true
  builders: true
  converters: true
  api_reference: true

  templates_data:
    GrafanaVersion: '%kind_registry_version%'
    ReleaseBranch: 'release_branch_name'
    CogVersion: 'snapshot'
    BuildTimestamp: '1733964347'

  languages:
    - go:
        package_root: '%go_package_root%'
        extra_files_templates:
          - '%__config_dir%/foundation-sdk/.cog/templates/go/extra'
        overrides_templates:
          - '%__config_dir%/foundation-sdk/.cog/templates/go/overrides'
        generate_json_marshaller: true
        generate_strict_unmarshaller: true
        generate_equal: true
        generate_validate: true
