# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/pipeline.json

debug: true

parameters:
  output_dir: './generated/%l'
  go_package_root: 'github.com/grafana/cog/generated/go'

inputs:
  - cue:
      entrypoint: '%__config_dir%/../schemas/sandbox'

output:
  directory: '%output_dir%'

  types: true
  builders: false
  converters: false
  api_reference: false

  templates_data:
    GrafanaVersion: '%kind_registry_version%'
    ReleaseBranch: 'release_branch_name'
    CogVersion: 'snapshot'
    BuildTimestamp: '1733964347'

  languages:
    - go:
        package_root: '%go_package_root%'
        generate_strict_unmarshaller: false
        generate_equal: false
        generate_validate: false
