# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/pipeline.json

debug: true

parameters:
  output_dir: './generated'
  kind_registry_path: '../kind-registry'
  kind_registry_version: 'v10.4.x'
  grafana_version: 'v10.4.x'
  go_package_root: 'github.com/grafana/cog/generated'

inputs:
  - cue:
      entrypoint: '/home/kevin/sandbox/work/cog/testdata/jennies/builders/struct_with_defaults/'
      cue_imports:
        - '/home/kevin/sandbox/work/kind-registry/grafana/next/common:github.com/grafana/grafana/packages/grafana-schema/src/common'

output:
  directory: '%output_dir%'

  types: true
  builders: true

  languages:
    - go:
        package_root: '%go_package_root%'
    - jsonschema: {}
    - openapi: {}
    - python:
        path_prefix: grafana_foundation_sdk
    - typescript: {}
    - java: {}
