# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/veneers.json

language: all

package: prometheus

builders:
  # Like the UI, support a "both instant and range" query
  # TODO: doesn't work because of a package issue in the `by_name` selector (Query is in the dashboard pkg?)
  - add_option:
      by_name: Query
      option:
        name: rangeAndInstant
        assignments:
          - path: range
            method: direct
            value: { constant: true }
          - path: instant
            method: direct
            value: { constant: true }

options:
  # Ensure that enabling "range query mode" disables other modes
  - unfold_boolean:
      by_builder: Query.range
      true_as: range
      false_as: notRange
  - omit: { by_builder: Query.notRange }
  - add_assignment:
      by_builder: Query.range
      assignment:
        path: instant
        method: direct
        value: { constant: false }

  # Ensure that enabling "instant query mode" disables other modes
  - unfold_boolean:
      by_builder: Query.instant
      true_as: instant
      false_as: notInstant
  - omit: { by_builder: Query.notInstant }
  - add_assignment:
      by_builder: Query.instant
      assignment:
        path: range
        method: direct
        value: { constant: false }
