{
 "title": "Blocky",
 "tags": [ "blocky" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(blocky_blocking_enabled,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Blocky [version](https://github.com/0xERR0R/blocky) number",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_build_info " }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "description": "current service state",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blocking_enabled" }
   ]
  },
  {
   "title": "Last list refresh",
   "type": "stat",
   "description": "Time since last list refresh",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() -blocky_last_list_group_refresh)/ sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Query Count Total",
   "type": "stat",
   "description": "Number of all queries. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total[$__range]))) "
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "stat",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[$__range])) / sum(increase(blocky_request_duration_ms_count[$__range]))"
    }
   ]
  },
  {
   "title": "Blacklist entries total",
   "type": "stat",
   "description": "Number of blacklist entries",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_blacklist_cache) / sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio",
   "type": "stat",
   "description": "Cache Hit/Miss ratio. 100 % means, all queries could be answered from the cache, 0% - all queries must be resolved via external DNS",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])) + sum(increase(blocky_cache_miss_count[$__range])))"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "description": "Number of occured errors",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total[$__range]))"
    }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "stat",
   "description": "Percentage of blocked queries",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[$__range])) / sum(increase(blocky_query_total[$__range])) "
    }
   ]
  },
  {
   "title": "Cache entries count",
   "type": "stat",
   "description": "Number of entries in the cache. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(blocky_cache_entry_count)/ sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\"})/sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Prefetch count",
   "type": "stat",
   "description": "Amount of performed DNS queries to prefetch cached queries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_prefetch_count[$__range])))"
    }
   ]
  },
  {
   "title": "Prefetch domain count",
   "type": "stat",
   "description": "Amount of unique domains in the prefetched cache",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_prefetch_domain_name_cache_count)/ sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Prefetch rate per min",
   "type": "stat",
   "description": "Amount of prefetch queries per minute",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetch_count[5m])) * 60"
    }
   ]
  },
  {
   "title": "Prefetch Hit ratio",
   "type": "stat",
   "description": "How many of cached entries were prefetched automatically",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_prefetch_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])))"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request rate per client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total[$__rate_interval])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total[$__range]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total[$__range]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, blocky_blacklist_cache) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (reason) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}