passes:
  - dataquery_identification: {}
  - unspec: {}

  #############
  # Dashboard #
  #############

  # These fields are incorrectly set as non-required in the CUE schema.
  # Loading a dashboard with these set to null will fail.
  - fields_set_required:
      fields: [
        dashboard.Dashboard.annotations,
        dashboard.Dashboard.templating,
      ]

  # Defined as an empty type in the CUE schemas.
  # It is also not used at all: references to this type are replaced by a "composable slot"
  - omit:
      objects: [
        dashboard.Target
      ]

  - name_anonymous_struct:
      field: dashboard.Dashboard.timepicker
      as: TimePicker

  - retype_field:
      field: dashboard.Panel.Targets
      as:
        kind: array
        array:
          value_type:
            kind: composable_slot
            composable_slot: { variant: dataquery }

  - dashboard_panels: {}

  ########################
  # Prometheus dataquery #
  ########################

  # Add a few missing fields.
  # This is meant to be removed once the schema is updated.
  - add_fields:
      to: prometheus.dataquery
      fields:
        - name: interval
          comments: ['An additional lower limit for the step parameter of the Prometheus query and for the', '`$__interval` and `$__rate_interval` variables.']
          type:
            kind: scalar
            scalar: { scalar_kind: string }

  ######################
  # testdata dataquery #
  ######################

  - name_anonymous_struct:
      field: testdata.SimulationQuery.key
      as: Key

  ##########
  # Others #
  ##########

  - cloudwatch: {}
  - google_cloud_monitoring: {}
  - library_panels: {}
