passes:
  - dataquery_identification: {}
  - unspec: {}

  #############
  # Dashboard #
  #############

  # These fields are incorrectly set as non-required in the CUE schema.
  # Loading a dashboard with these set to null will fail.
  - fields_set_required:
      fields: [
        dashboard.Dashboard.annotations,
        dashboard.Dashboard.templating,
      ]

  # Defined as an empty type in the CUE schemas.
  # It is also not used at all: references to this type are replaced by a "composable slot"
  - omit:
      objects: [
        dashboard.Target
      ]

  - dashboard_panels: {}
  - dashboard_targets: {}
  - dashboard_timepicker: {}

  ########################
  # Prometheus dataquery #
  ########################
  - add_fields:
      to: prometheus.dataquery
      fields:
        - name: interval
          comments: ['An additional lower limit for the step parameter of the Prometheus query and for the", "`$__interval` and `$__rate_interval` variables.']
          type:
            kind: scalar
            scalar: {scalar_kind: string}

  ##########
  # Others #
  ##########

  - cloudwatch: {}
  - google_cloud_monitoring: {}
  - library_panels: {}
  - test_data: {}
