# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/veneers.json

language: all

package: sandbox

builders: ~

options:
  - map_to_index:
      by_name: Sandbox.annotations
