# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/veneers.json

language: all

package: team

builders:
  ################
  # Constructors #
  ################
  - promote_options_to_constructor:
      by_name: Team
      options: [name]

options: ~
