# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/veneers.json

language: go

package: tempo

builders: ~

options:
  - struct_fields_as_arguments:
      by_name: TraceqlFilter.value
      fields: [ ArrayOfString ]
  - rename_arguments:
      by_name: TraceqlFilter.value
      as: [values]
