site_name: Grafana Foundation SDK

repo_name: "grafana/grafana-foundation-sdk"
repo_url: "https://github.com/grafana/grafana-foundation-sdk"

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
        - name: go
          lang: go
          options:
            startinline: true
        - name: typescript
          lang: typescript
          options:
            startinline: true
        - name: python
          lang: python
          options:
            startinline: true
  - pymdownx.superfences
  - toc:
      permalink: 🔗

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  custom_dir: overrides

  logo: "assets/logo.svg"

  palette:
    - accent: "deep orange"
      media: "(prefers-color-scheme: light)"
      primary: "black"
      scheme: "default"
      toggle:
        icon: "material/toggle-switch-off-outline"
        name: "Switch to dark mode"
    - accent: "deep-orange"
      media: "(prefers-color-scheme: dark)"
      primary: "black"
      scheme: "slate"
      toggle:
        icon: "material/toggle-switch"
        name: "Switch to light mode"

extra_css: 
  - "assets/custom.css"
