name: Python CI
on:
  pull_request: ~

env:
  PYTHON_VERSION: '3.12'

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./python

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python {{ `${{ env.PYTHON_VERSION }}` }}
        uses: actions/setup-python@v5
        with:
          python-version: {{ `${{ env.PYTHON_VERSION }}` }}

      - name: Install mypy
        run: python3 -m pip install mypy

      - name: Lint generated Python code
        run: mypy .
